### ISSUE TITLE
ImportError: cannot import name 'legacy_round' from 'textstat.textstat' 

### ISSUE THREAD

**Issue by Eeman1113** [shivam5992/textstat#186]
so I am training to import legacy its not working on ether google colab or in m1 Mac even after installing all the libs needed <br>
This is my code:<br>
`import spacy
import textstat
from textstat.textstat import textstatistics<br>
from textstat.textstat import legacy_round`

This is my output:<br>
`Traceback (most recent call last):
  File "/Users/eemanmajumder/code_shit/dashboard_for_work.py", line 32, in <module><br>
    from textstat.textstat import legacy_round<br>
ImportError: cannot import name 'legacy_round' from 'textstat.textstat' (/opt/homebrew/lib/python3.9/site
packages/textstat/textstat.py)`

**Comment by alxwrd** [comment]
Hi @Eeman1113,

Thank you for raising this. In the lastest release ([0.7.3](https://github.com/shivam5992/textstat/releases/tag/0.7.3)), the function `legacy_round` was moved to be a private memeber of the `textstatistics`.

https://github.com/shivam5992/textstat/blob/9aab97cd832f67b7c6f198ae87b0ff4f566ecb4b/textstat/textstat.py#L106-L133

As a work around you can:

```python
from textstat import textstat

legacy_round = textstat._legacy_round
```

The function `legacy_round` is an implementation detail for `textstat`, and shouldn't be relied upon (which is why it has moved).

**Comment by Eeman1113** [comment]
hey thanks man
