### ISSUE TITLE
Returing wrong values!

### ISSUE THREAD

**Issue by accessgopal** [shivam5992/textstat#28]
_The function "flesch_reading_ease" is returning a wrong value._ 

As per Wikipedia ([Click Here](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests)) 

"The cat sat on the mat." should score 116 but, the function is returning "**124.61**" 

According to Wikipedia "The highest (easiest) readability score possible is **121.22**" 

I did not get a chance to evaluate the function but, this is my quick evaluation. Probably do it later! 

PS: Nice work! Loved the functions you have added in the package, Cheers.

**Comment by alxwrd** [comment]
@accessgopal This appears to be an old issues with the function `syllable_count`. It wasn't calculating the syllable count correctly. This has been fixed in commit f3c39dd, but it hasn't been pushed to pypi yet.

**Pypi package**
```
$ pip install textstat
$ python
>>> from textstat import textstat
>>> textstat.textstat.flesch_reading_ease("The cat sat on the mat.")
124.61
```

**Git clone**
```
$ git clone https://github.com/shivam5992/textstat.git
$ cd textstat
$ python setup.py build
$ python setup.py install
$ python
>>> from textstat import textstat
>>> textstat.textstat.flesch_reading_ease("The cat sat on the mat.")
116.5
```

@shivam5992 might it be worth adding the latest changes to pypi?

**Comment by shivam5992** [comment]
@alxwrd Thanks 
I will add latest changes to pypi.

**Comment by shivam5992** [comment]
Updated to Pypi.
