### ISSUE TITLE
difficult_words bugs like case-sensitivity and marks at the end of sentence

### ISSUE THREAD

**Issue by AliGolmirzaei** [shivam5992/textstat#31]
def difficult_words(self, text)
extracts the words by simply splitting the text by using spaces. but this can lead to a condition that "." (or other marks) be part of a word. For example, I input a sentence with word "lives." at end of it. Although "lives" is in the easy word list, it looks it as a difficult word. Another problem regarding this dot is that it sees paperwork. and paperwork as two different words which is not true
Another problem is case-sensitivity. This method sees Lives as a difficult word which is not true.
I suggest using a regex for extracting the words (if you want it to be stand-alone) or nltk if you want it to be perfect.

**Comment by AliGolmirzaei** [comment]
I have an old regex that I created for one of my projects. Maybe it helps you
word_re = re.compile(ur'([\w--[0-9_]][\u0027\u2018\u2019\w--[0-9_]]*[\w--[0-9_]])', re.UNICODE|re.V1)
it uses the regex module

**Comment by alxwrd** [comment]
@AliGolmirzaei good catch.

I would probably suggest shortening the regex to `[\w\-'‘’]+` as the 3 character sets miss out single letter words like "a".

Also after quick scan over the words in `easy_words.txt` ([most noteably with I](https://github.com/shivam5992/textstat/blob/master/textstat/easy_words.txt#L1340)) some of them are capitialised. So this list would need to be changed to all lowercase.

So work for this would be:
- Split the input on an appropriate regex to extract all words.
- Make all words in `easy_words.txt` lowercase.
- Make the comparison `if value not in easy_word_set` ignore case.

There are also a couple of other places where `text.split()` is done, so these might need changing as well.

Finally, this change will probably cause some tests to start failing, so that will need fixing up.

@AliGolmirzaei would you be interested on working on the changes?

**Comment by alxwrd** [comment]
Make all words in `easy_words.txt` lowercase completed in #33.
