### ISSUE TITLE
Different behavior between 0.3.1 and 0.4.1

### ISSUE THREAD

**Issue by chandlerzuo** [shivam5992/textstat#42]
I have noticed that 0.3.1 and 0.4.1 have quite different behaviors for certain functions. The following is the comparison on flesch_reading_ease:

Version 0.3.1:
`from textstat.textstat import textstat`
`textstat.flesch_reading_ease("Python package to calculate statistics from text to determine readability, complexity and grade level of a particular corpus.")`
`>> 10.91`

Version 0.4.1:
`from textstat.textstat import textstat `
`textstat.flesch_reading_ease("Python package to calculate statistics from text to determine readability, complexity and grade level of a particular corpus.")`
`>> 19.37`

My guess is that this is from the change in calculating syllabuses, but I am not sure until I dig thoroughly through the commit history. Have you noticed this behavior? Is there an interpretation?

It seems to me that 0.4.1's calculation is more robust / scientific. But it would be good to maintain backward compatibility during version updates.  Is there, or do you plan to develop, an option in 0.4.x that allows users to regenerate the results in 0.3.1?

**Comment by alxwrd** [comment]
hi @chandlerzuo :wave:!

You are correct that the differences you are seeing are because of changes to textstat's syllable calculation, and other things.

I think it's fair to say the goal for textstat is to provide as accurate as possible information about a given piece of text.

Therefore, I don't think it would be suitable to support old behaviours/calculations going forward, as ultimately, some calculations in 0.3.1 were incorrect.

If you are doing long running analysis and need the behaviour of the previous version to normalise your results, or want to get the same results again, you can target versions in **pip** by using `pip install textstat==0.3.1`. For managing versions between different projects, I'd recommend using  [pipenv](https://github.com/pypa/pipenv).
