### ISSUE TITLE
Allow to change language in syllable_count to languages supported by Pyphen

### ISSUE THREAD

**Issue by sairampillai** [shivam5992/textstat#93]
Currently syllable_count takes a lang argument which is set to 'en_US' by default. This can be changed to take lang argument input during function call. Pyphen allows for many language options. Some of the languages used might be effected by having a different sentence delimited other than a period but it should work for some cases and further improvement can be made.

**Comment by alxwrd** [comment]
Hi @sairampillai

Thank you for raising the issue.

I'm not sure I understand. The default for `syllable_count` is "en_US", but you can change it by `syllable_count(text, lang="<other_lang>"`.

I don't know how relevent it would be to have the `lang` argument as a pass through to other methods because the readability methods are based on research that was done against the English language.

**Comment by sairampillai** [comment]
I see. Thank you @alxwrd . I was thinking if the lang argument could be passed from the function flesch_kincaid_grade itself. And alongwith them update the parameters of the formula for experimental purposes. But for now I will proceed with making the changes locally.

**Comment by alxwrd** [comment]
Related to #94

**Comment by alxwrd** [comment]
I'm going to close this in favour of keeping the more general issue.
